name: Build
on:
  push:
    branches:
      - v3
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install --include=dev

      - name: Build
        run: npm run build

      - name: Weird
        run: node github_actions.js

      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Build changes
          branch: build
          create_branch: true